# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCAsianBarrierPortfolioPricer <- function(expiry = 5.0 / 12.0, spot = 115, vol = 0.25, r = 0.05, d = 0.0, numberOfPaths = 1000000L, numberOfDates = 126L, barrier = 0.8 * 115) {
    .Call(`_OptionPricer_MCAsianBarrierPortfolioPricer`, expiry, spot, vol, r, d, numberOfPaths, numberOfDates, barrier)
}

