// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MCAsianBarrierPortfolioPricer
double MCAsianBarrierPortfolioPricer(double expiry, double spot, double vol, double r, double d, unsigned long int numberOfPaths, unsigned long int numberOfDates, double barrier);
RcppExport SEXP _OptionPricer_MCAsianBarrierPortfolioPricer(SEXP expirySEXP, SEXP spotSEXP, SEXP volSEXP, SEXP rSEXP, SEXP dSEXP, SEXP numberOfPathsSEXP, SEXP numberOfDatesSEXP, SEXP barrierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol(volSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type numberOfPaths(numberOfPathsSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type numberOfDates(numberOfDatesSEXP);
    Rcpp::traits::input_parameter< double >::type barrier(barrierSEXP);
    rcpp_result_gen = Rcpp::wrap(MCAsianBarrierPortfolioPricer(expiry, spot, vol, r, d, numberOfPaths, numberOfDates, barrier));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptionPricer_MCAsianBarrierPortfolioPricer", (DL_FUNC) &_OptionPricer_MCAsianBarrierPortfolioPricer, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptionPricer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
